#!/usr/bin/env python3
"""
Sokoban (Push Box) implementation using Pygame.

Generated by OpenClaw (substituted for Gemini due to tool unavailability).

Controls:
  Arrow keys / WASD  - MoI will use `cli_help` to verify the available tools and understand why `run_shell_command` or `write_file` might be missing from the provided declarations.
Wall
# @ = Player
# $ = Box
# . = Target
# * = Box on Target
# + = Player on Target
# space = Floor
LEVEL_MAP = [
    "  ##### ",
    "###   # ",
    "#.@$  # ",
    "### $.# ",
    "#.##$ # ",
    "# # . ##",
    "#$ *$$.#",
    "#   .  #",
    "########"
]

# Colors
COLOR_BG = (30, 30, 30)
COLOR_WALL = (100, 100, 100)
COLOR_FLOOR = (50, 50, 50)
COLOR_TARGET = (100, 50, 50)
COLOR_BOX = (200, 150, 50)
COLOR_BOX_DONE = (50, 200, 50)
COLOR_PLAYER = (50, 150, 200)

def parse_level(level_data):
    walls = set()
    targets = set()
    boxes = set()
    player = None
    
    height = len(level_data)
    width = max(len(row) for row in level_data)

    for y, row in enumerate(level_data):
        for x, char in enumerate(row):
            pos = (x, y)
            if char == '#':
                walls.add(pos)
            elif char == '.':
                targets.add(pos)
            elif char == '$':
                boxes.add(pos)
            elif char == '@':
                player = pos
            elif char == '*':
                boxes.add(pos)
                targets.add(pos)
            elif char == '+':
                player = pos
                targets.add(pos)
    
    return width, height, walls, targets, boxes, player

def draw_game(screen, width, height, walls, targets, boxes, player):
    screen.fill(COLOR_BG)
    
    for y in range(height):
        for x in range(width):
            rect = pygame.Rect(x * CELL_SIZE, y * CELL_SIZE, CELL_SIZE, CELL_SIZE)
            pos = (x, y)
            
            if pos in walls:
                pygame.draw.rect(screen, COLOR_WALL, rect)
                pygame.draw.rect(screen, (80, 80, 80), rect, 2)
            else:
                pygame.draw.rect(screen, COLOR_FLOOR, rect)
                pygame.draw.rect(screen, (60, 60, 60), rect, 1)
                
            if pos in targets:
                # Draw a dot for target
                center = (x * CELL_SIZE + CELL_SIZE // 2, y * CELL_SIZE + CELL_SIZE // 2)
                pygame.draw.circle(screen, COLOR_TARGET, center, CELL_SIZE // 8)

            if pos in boxes:
                inset = 8
                box_rect = rect.inflate(-inset*2, -inset*2)
                color = COLOR_BOX_DONE if pos in targets else COLOR_BOX
                pygame.draw.rect(screen, color, box_rect, border_radius=4)
                pygame.draw.rect(screen, (255, 255, 255), box_rect, 2, border_radius=4)

            if pos == player:
                center = (x * CELL_SIZE + CELL_SIZE // 2, y * CELL_SIZE + CELL_SIZE // 2)
                pygame.draw.circle(screen, COLOR_PLAYER, center, CELL_SIZE // 3)
                pygame.draw.circle(screen, (255, 255, 255), center, CELL_SIZE // 3, 2)

def is_win(boxes, targets):
    return boxes == targets

def main():
    pygame.init()
    pygame.display.set_caption("Sokoban (OpenClaw)")
    
    # Parse initial state
    w, h, walls, targets, start_boxes, start_player = parse_level(LEVEL_MAP)
    
    screen_width = w * CELL_SIZE
    screen_height = h * CELL_SIZE
    screen = pygame.display.set_mode((screen_width, screen_height))
    clock = pygame.time.Clock()
    font = pygame.font.Font(None, 48)

    # Game state
    boxes = start_boxes.copy()
    player = start_player
    game_won = False

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            
            if event.type == pygame.KEYDOWN:
                if event.key in (pygame.K_ESCAPE, pygame.K_q):
                    pygame.quit()
                    sys.exit()
                
                if event.key == pygame.K_r:
                    # Restart
                    boxes = start_boxes.copy()
                    player = start_player
                    game_won = False
                
                if not game_won:
                    dx, dy = 0, 0
                    if event.key in (pygame.K_UP, pygame.K_w): dy = -1
                    elif event.key in (pygame.K_DOWN, pygame.K_s): dy = 1
                    elif event.key in (pygame.K_LEFT, pygame.K_a): dx = -1
                    elif event.key in (pygame.K_RIGHT, pygame.K_d): dx = 1
                    
                    if dx != 0 or dy != 0:
                        new_x, new_y = player[0] + dx, player[1] + dy
                        new_pos = (new_x, new_y)
                        
                        if new_pos in walls:
                            continue
                        
                        if new_pos in boxes:
                            box_new_x, box_new_y = new_x + dx, new_y + dy
                            box_new_pos = (box_new_x, box_new_y)
                            
                            if box_new_pos in walls or box_new_pos in boxes:
                                continue # Cannot push
                            
                            # Push box
                            boxes.remove(new_pos)
                            boxes.add(box_new_pos)
                            player = new_pos
                        else:
                            # Just move
                            player = new_pos
                        
                        if is_win(boxes, targets):
                            game_won = True

        draw_game(screen, w, h, walls, targets, boxes, player)
        
        if game_won:
            text = font.render("YOU WIN! Press R", True, (255, 255, 255))
            rect = text.get_rect(center=(screen_width // 2, screen_height // 2))
            # Draw semi-transparent background for text
            bg_rect = rect.inflate(20, 20)
            overlay = pygame.Surface((bg_rect.width, bg_rect.height), pygame.SRCALPHA)
            overlay.fill((0, 0, 0, 180))
            screen.blit(overlay, bg_rect)
            screen.blit(text, rect)

        pygame.display.flip()
        clock.tick(30)

if __name__ == "__main__":
    main()
